export const GET_IN_DESIBYTES='GET_IN_DESIBYTES';
export const DESIBYTES_COMPLETE='DESIBYTES_COMPLETE';
export const DESIBYTES_FAILED ='DESIBYTES_FAILED';
export const DESIBYTES_DETAIL_IN_REQUEST='DESIBYTES_DETAIL_IN_REQUEST';
export const DESIBYTES_DETAIL_IN_COMPLETE ='DESIBYTES_DETAIL_IN_COMPLETE';
export const DESIBYTES_DETAIL_IN_FAILED ='DESIBYTES_DETAIL_IN_FAILED';