export const NEGATIVESTOCK_IN_REQUEST='NEGATIVESTOCK_IN_REQUEST';
export const NEGATIVESTOCK_IN_COMPLETE='NEGATIVESTOCK_IN_COMPLETE';
export const NEGATIVESTOCK_IN_FAILED='NEGATIVESTOCK_IN_FAILED';
export const ZEROLIST_IN_REQUEST='ZEROLIST_IN_REQUEST';
export const ZEROLIST_IN_COMPLETE='ZEROLIST_IN_COMPLETE';
export const ZEROLIST_IN_FAILED='ZEROLIST_IN_FAILED';