import React,{} from 'react';

const Brands =[
    {id:'1', name:'24 Mantra'},
    {id:'2', name:'5 Elements'},
    {id:'3', name:'777'},
    {id:'4', name:'A+'},
    {id:'5', name:'Aachi'},
    {id:'6', name:'Abhiruchi'},
    {id:'7', name:'Abhishek'},
    {id:'8', name:'Actionware'},
    {id:'9', name:'Adusol'},
    {id:'10', name:'Adyar'},
    {id:'11', name:'Adyar Ananda Bhavan'},
    {id:'12', name:'Aeroplane'},
    {id:'13', name:'Agro'},
    {id:'14', name:'Ahmed'},
    {id:'15', name:'Aisha'},
    {id:'16', name:'Albarakah'},
    {id:'17', name:'All Fresh'},
    {id:'18', name:'Allegro'},
    {id:'19', name:'Aloevine'},
    {id:'20', name:'Altaj'},
    {id:'21', name:'Ambika Appalam'},
    {id:'22', name:'American'},
    {id:'23', name:'Ammas'},
    {id:'24', name:'Amrutanjan'},
    {id:'25', name:'Amul'},
    {id:'26', name:'Anand'},
    {id:'27', name:'Anand Bhog'},
    {id:'28', name:'Anand Bhogh'},
    {id:'29', name:'Anarkali'},
    {id:'30', name:'Ancient Veda'},
    {id:'31', name:'Angur'},
    {id:'32', name:'Anil'},
    {id:'33', name:'Anil Ghoshs'},
    {id:'34', name:'Anjali'},
    {id:'35', name:'Ankur'},
    {id:'36', name:'Annapurna'},
    {id:'37', name:'Anoos'},
    {id:'38', name:'Apex'},
    {id:'39', name:'Aroy'},
    {id:'40', name:'Ashirwad'},
    {id:'41', name:'Ashoka'},
    {id:'42', name:'Ashwin'},
    {id:'43', name:'Ashwini'},
    {id:'44', name:'Asian Foods'},
    {id:'45', name:'Astagandh'},
    {id:'46', name:'Avdhoot'},
    {id:'47', name:'Ayur'},
    {id:'48', name:'Babus'},
    {id:'49', name:'Badri'},
    {id:'50', name:'Badshah'},
    {id:'51', name:'Bahar'},
    {id:'52', name:'Bajaj'},
    {id:'53', name:'Balaji'},
    {id:'54', name:'Balle Balle'},
    {id:'55', name:'Bambino'},
    {id:'56', name:'Banjara'},
    {id:'57', name:'Banne Nawabs'},
    {id:'58', name:'Bansi'},
    {id:'59', name:'Basic Ayurveda'},
    {id:'60', name:'Bedekar'},
    {id:'61', name:'Beezy'},
    {id:'62', name:'Best'},
    {id:'63', name:'Bhagwatis'},
    {id:'64', name:'Bhakti'},
    {id:'65', name:'Bhalle bhalle'},
    {id:'66', name:'Bhikaram Chandmal'},
    {id:'67', name:'Big joy'},
    {id:'68', name:'Bigen'},
    {id:'69', name:'Bikaji'},
    {id:'70', name:'Birds'},
    {id:'71', name:'Black Gold'},
    {id:'72', name:'Black Rose'},
    {id:'73', name:'Blue Bird'},
    {id:'74', name:'Bombay magic'},
    {id:'75', name:'Boost'},
    {id:'76', name:'Boroline'},
    {id:'77', name:'Boss'},
    {id:'78', name:'Bounty'},
    {id:'79', name:'Bournvita'},
    {id:'80', name:'Bouurnvita'},
    {id:'81', name:'Brar'},
    {id:'82', name:'Bright'},
    {id:'83', name:'Britannia'},
    {id:'84', name:'Brook Bond'},
    {id:'85', name:'Brown & polson'},
    {id:'86', name:'Bru'},
    {id:'87', name:'Bru Gold'},
    {id:'88', name:'BryIcream'},
    {id:'89', name:'Burnol'},
    {id:'90', name:'Cadbury'},
    {id:'91', name:'Cadbuty'},
    {id:'92', name:'Cavins'},
    {id:'93', name:'Century'},
    {id:'94', name:'Chandan'},
    {id:'95', name:'Chandrika'},
    {id:'96', name:'Chaokoh'},
]

export default Brands;