export const GET_IN_REQUEST='GET_IN_REQUEST';
export const GET_IN_COMPLETE= 'GET_IN_COMPLETE';
export const GET_IN_FAILED='GET_IN_FAILED';
export const BRAND_IN_REQUEST='BRAND_IN_REQUEST';
export const BRAND_IN_COMPLETE='BRAND_IN_COMPLETE';
export const BRAND_IN_FAILURE='BRAND_IN_FAILURE';
export const DEPARTMENT_PRODUCT_REQUEST='DEPARTMENT_PRODUCT_REQUEST';
export const DEPARTMENT_PRODUCT_COMPLETE='DEPARTMENT_PRODUCT_COMPLETE';
export const DEPARTMENT_PRODUCT_FAILED='DEPARTMENT_PRODUCT_FAILED';
export const DEPARTMENT_PRODUCT_FILTER='DEPARTMENT_PRODUCT_FILTER';

export const ADDITEM_IN_REQUEST='ADDITEM_IN_REQUEST';
export const ADDITEM_IN_COMPLETE='ADDITEM_IN_COMPLETE';
export const ADDITEM_IN_FAILED ='ADDITEM_IN_FAILED';

export const DEPARTMENT_PRODUCT_REQUEST_NEW='DEPARTMENT_PRODUCT_REQUEST_NEW';
export const DEPARTMENT_PRODUCT_COMPLETE_NEW='DEPARTMENT_PRODUCT_COMPLETE_NEW';
export const DEPARTMENT_PRODUCT_FAILED_NEW='DEPARTMENT_PRODUCT_FAILED_NEW';