export const SNACK_IN_REQUEST='SNACK_IN_REQUEST';
export const SNACK_IN_COMPLETED='SNACK_IN_COMPLETED';
export const SNACK_IN_FAILED='SNACK_IN_FAILED';

export const HIT_IN_SNACK='HIT_IN_SNACK';
export const HIT_IN_SUCCESS='HIT_IN__SUCCESS';
export const HIT_IN_FAILED='HIT_IN_FAILED';
