export const CREATELIST_IN_REQUEST='CREATELIST_IN_REQUEST';
export const CREATELIST_IN_COMPLETE='CREATELIST_IN_COMPLETE';
export const CREATELIST_IN_FAILED='CREATELIST_IN_FAILED';
export const GETLIST_IN_REQUEST='GETLIST_IN_REQUEST';
export const GETLIST_IN_COMPLETE='GETLIST_IN_COMPLETE';
export const GETLIST_IN_FAILED='GETLIST_IN_FAILED';

export const DELETELIST_IN_REQUEST='DELETELIST_IN_REQUEST';
export const DELETELIST_IN_COMPLETE='DELETELIST_IN_COMPLETE';
export const DELETELIST_IN_FAILED='DELETELIST_IN_FAILED';

export const DETAILS_IN_REQUEST='DETAILS_IN_REQUEST';
export const DETAILS_IN_COMPLETE='DETAILS_IN_COMPLETE';
export const DETAILS_IN_FAILED='DETAILS_IN_FAILED';

export const SELECTEDLIST_ID_COMPLETE= 'SELECTEDLIST_ID_COMPLETE';
