export const ORGANIC_IN_REQUEST='ORGANIC_IN_REQUEST';
export const ORGANIC_IN_SUCCESS='ORGANIC_IN_SUCCESS';
export const ORGANIC_IN_FAILURE='ORGANIC_IN_FAILURE';
export const ORGANIC_FILTER_REQUEST='ORGANIC_FILTER_REQUEST';
export const ORGANIC_FILTER_COMPLETE='ORGANIC_FILTER_COMPLETE';