export const COUPON_IN_REQUEST='COUPON_IN_REQUEST';
export const COUPON_IN_COMPLETE='COUPON_IN_COMPLETE';
export const COUPON_IN_FAILED= 'COUPON_IN_FAILED';

export const MYCOUPON_IN_REQUEST='MYCOUPON_IN_REQUEST';
export const MYCOUPON_IN_COMPLETE='MYCOUPON_IN_COMPLETE';
export const MYCOUPON_IN_FAILED= 'MYCOUPON_IN_FAILED';
export const ALL_COUPON='ALL_COUPON';
export const MY_COUPON='MY_COUPON';