export const TOPMOVER_IN_REQUEST='TOPMOVER_IN_REQUEST';
export const TOPMOVER_IN_COMPLETE='TOPMOVER_IN_COMPLETE';
export const TOPMOVER_IN_FAILED ='TOPMOVER_IN_FAILED';
export const TOPMOVER_FILTER_REQUEST='TOPMOVER_FILTER_REQUEST';
export const TOPMOVER_FILTER_COMPLETE='TOPMOVER_FILTER_COMPLETE';
export const TOPMOVER_FILTER_FAILED ='TOPMOVER_FILTER_FAILED';