export const REWARDS_TRANSTACTION_REQUEST='REWARDS_TRANSTACTION_REQUEST';
export const REWARDS_TRANSTACTION_COMPLETE='REWARDS_TRANSTACTION_COMPLETE';
export const REWARDS_TRANSTACTION_FAILED='REWARDS_TRANSTACTION_FAILED';

export const MYREWARDS_IN_REQUEST='MYREWARDS_IN_REQUEST';
export const MYREWARDS_IN_COMPLETE='MYREWARDS_IN_COMPLETE';
export const MYREWARDS_IN_FAILED ='MYREWARDS_IN_FAILED';