export const GET_REMINDER_REQUEST='GET_REMINDER_REQUEST';
export const GET_REMINDER_COMPLETE='GET_REMINDER_COMPLETE';
export const GET_REMINDER_FAILED='GET_REMINDER_FAILED';
export const REMINDER_SHORT_COMPLETE='REMINDER_SHORT_COMPLETE';

export const EDIT_PROFILE_IN_REQUEST='EDIT_PROFILE_IN_REQUEST';
export const EDIT_PROFILE_IN_COMPLETE='EDIT_PROFILE_IN_COMPLETE';
export const EDIT_PROFILE_IN_FAILED='EDIT_PROFILE_IN_FAILED';

export const DELETE_NOT_REQUEST_PROD='DELETE_NOT_REQUEST_PROD';
export const DELETE_NOT_COMPLETED_PROD='DELETE_NOT_COMPLETED_PROD';
export const DELETE_NOT_FAILED_PROD='DELETE_NOT_FAILED_PROD';