export const STOCKDETAIL_IN_REQUEST='STOCKDETAIL_IN_REQUEST';
export const STOCKDETAIL_IN_COMPLETE='STOCKDETAIL_IN_COMPLETE';
export const STOCKDETAIL_IN_FAILED='STOCKDETAIL_IN_FAILED';

export const STOCKUPDATE_IN_REQUEST='STOCKUPDATE_IN_REQUEST';
export const STOCKUPDATE_IN_COMPLETE='STOCKUPDATE_IN_COMPLETE';
export const STOCKUPDATE_IN_FAILED='STOCKUPDATE_IN_FAILED';