export const NOTIFICATION_GET_SETTING_REQUEST = 'NOTIFICATION_GET_SETTING_REQUEST';
export const NOTIFICATION_GET_SETTING_COMPLETED = 'NOTIFICATION_GET_SETTING_COMPLETED';
export const NOTIFICATION_GET_SETTING_FAILURE = 'NOTIFICATION_GET_SETTING_FAILURE';
export const NOTIFICATION_SETTING_UPDATE_REQUEST = 'NOTIFICATION_SETTING_UPDATE_REQUEST';
export const NOTIFICATION_SETTING_UPDATE_COMPLETE = 'NOTIFICATION_SETTING_UPDATE_COMPLETE';
export const NOTIFICATION_SETTING_UPDATE_FAILED = 'NOTIFICATION_SETTING_UPDATE_FAILED';