export const NEWARRIVAL_IN_REQUEST='NEWARRIVAL_IN_REQUEST';
export const NEWARRIVAL_IN_COMPLETE='NEWARRIVAL_IN_COMPLETE';
export const NEWARRIVAL_IN_FAILURE='NEWARRIVAL_IN_FAILURE';
export const FILTER_IN_REQUEST='FILTER_IN_REQUEST';
export const FILTER_IN_COMPLETE='FILTER_IN_COMPLETE';
export const LOCATION_IN_REQUEST='LOCATION_IN_REQUEST';
export const LOCATION_IN_COMPLETE='LOCATION_IN_COMPLETE';
export const LOCATION_IN_FAILED='LOCATION_IN_FAILED';