export const PURCHASE_IN_REQUEST='PURCHASE_IN_REQUEST';
export const PURCHASE_IN_COMPLETE='PURCHASE_IN_COMPLETE';
export const PURCHASE_IN_FAILED='PURCHASE_IN_FAILED';

export const INVOICE_IN_REQUEST='INVOICE_IN_REQUEST';
export const INVOICE_IN_COMPLETE='INVOICE_IN_COMPLETE';
export const INVOICE_IN_FAILED='INVOICE_IN_FAILED';