export const PRODUCTSEARCH_IN_REQUEST='PRODUCTSEARCH_IN_REQUEST';
export const PRODUCTSEARCH_IN_COMPLETE='PRODUCTSEARCH_IN_COMPLETE';
export const PRODUCTSEARCH_IN_FAILED='PRODUCTSEARCH_IN_FAILED';
export const PRODUCTSEARCH_LOCAL_REQUEST='PRODUCTSEARCH_LOCAL_REQUEST';
export const PRODUCTSEARCH_LOCAL_COMPLETE='PRODUCTSEARCH_LOCAL_COMPLETE';
export const PRODUCTSEARCH_LOCAL_FAILED='PRODUCTSEARCH_LOCAL_FAILED';
export const PRODUCTSEARCH_IN_CLEAR='PRODUCTSEARCH_IN_CLEAR';
export const PRODUCTSEARCH_IN_DATAHIDE='PRODUCTSEARCH_IN_DATAHIDE';

export const PRODUCTSEARCH_IN_SEARCHNAME='PRODUCTSEARCH_IN_SEARCHNAME';