export const DETAIL_IN_REQUEST='DETAIL_IN_REQUEST';
export const DETAIL_IN_COMPLETE='DETAIL_IN_COMPLETE';
export const DETAIL_IN_FAILURE='DETAIL_IN_FAILURE';

export const DETAIL_ADDITEM_COMPLETE='DETAIL_ADDITEM_COMPLETE';