export const GET_VALUE_REQUEST='GET_VALUE_REQUEST';
export const GET_VALUE_COMPLETE='GET_VALUE_COMPLETE';
export const GET_VALUE_FAILED='GET_VALUE_FAILED';

export const GET_NOTIFICATION_TYPE_COMPLETE='GET_NOTIFICATION_TYPE_COMPLETE';