export const SALES_REPORT_REQUEST= 'SALES_IN_STARTED';
export const SALES_REPORT_SUCCESS ='SALES_IN_COMPLETED';
export const SALES_REPORT_FAILURE ='SALES_IN_FAILED';
export const DEPARTMENT_REPORT_REQUEST='DEPART_IN_STARTED';
export const DEPARTMENT_REPORT_SUCCESS= 'DEPART_IN_COMPLETED';
export const DEPARTMENT_REPORT_FAILURE= 'DEPART_IN_FAILED';


